#!/bin/bash
module="nvidia" #Module we're checking against to determine if an accelerator is available.
gpu_id="0000:04:00.0"
basepath="/sys/bus/pci/drivers"
if [[ "$1" == *"="* ]];
    then
        for var in "$@"; do
            if [[ "$var" == "$1" ]]; then
                IFS=$'\n' ENVVARS=( $(xargs -n1 <<< $1) )
                #parse out the first var as args
            else
                new_args+=($var)
                #yeet the environment variables
            fi
        done
        for key in ${ENVVARS[@]}
        do
            #export the environment variables
            export $key
        done
    else
        new_args=$@
fi

if [ -d "$basepath/$module/$gpu_id" ]
    then
        printf "Faster GPU is available, setting environment variables to use it.\n"
        #Export nvidia requirements
        export DRI_PRIME=$gpu_id __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia export VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/nvidia_icd.json 
    else
        printf "Faster GPU is not available. Check if you're passing it through to your VM or if you remembered to use the GPU swap script.\n"
fi
#run the program
"${new_args[@]}"
